services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - ai-engine

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - AI_SERVICE_URL=http://ai-engine:8000
      - DB_HOST=souqyemen.cszggy2wqm5a.us-east-1.rds.amazonaws.com
      - DB_USER=root
      - DB_PASSWORD=Zoherama1122
      - DB_NAME=souqyemen
    depends_on:
      - ai-engine

  ai-engine:
    build:
      context: ./FastAPI
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=souqyemen.cszggy2wqm5a.us-east-1.rds.amazonaws.com
      - DB_USER=root
      - DB_PASSWORD=Zoherama1122
      - DB_NAME=souqyemen
