import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import { useTranslation } from "react-i18next";
import {
  Users,
  Store,
  Package,
  ShoppingCart,
  DollarSign,
  Download,
  Trophy,
} from "lucide-react";

export default function AdminReportsTab() {
  const [report, setReport] = useState(null);
  const { t } = useTranslation();

  useEffect(() => {
    fetchReport();
  }, []);

  const fetchReport = async () => {
    try {
      const token = localStorage.getItem("token");
      const res = await axios.get("https://souqyemen.store/api/admin/report", {
        headers: { Authorization: `Bearer ${token}` },
      });
      setReport(res.data);
    } catch (err) {
      console.error("Report error:", err);
    }
  };

  const handleDownloadPDF = () => {
    if (!report) return;
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();

    // ==========================================
    // 1. BRANDED HEADER (Souq Yemen Red)
    // ==========================================
    pdf.setFillColor(162, 47, 41); // #a22f29
    pdf.rect(0, 0, pageWidth, 45, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(24);
    pdf.text("SOUQ YEMEN", pageWidth / 2, 22, { align: "center" });

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text("Official Platform Analytics Report", pageWidth / 2, 32, {
      align: "center",
    });

    // ==========================================
    // 2. METADATA
    // ==========================================
    let y = 60;
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(10);
    // Note: We hardcode English here to prevent Arabic encoding crashes in jsPDF
    pdf.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, y);
    pdf.text(`Generated By: System Administrator`, 14, y + 6);

    // Divider line
    y += 12;
    pdf.setDrawColor(220, 220, 220);
    pdf.line(14, y, pageWidth - 14, y);

    // ==========================================
    // 3. PLATFORM OVERVIEW (Stats)
    // ==========================================
    y += 15;
    pdf.setTextColor(30, 30, 30);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Platform Overview", 14, y);

    y += 12;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    // Left Column
    pdf.text(`Total Users:`, 14, y);
    pdf.text(`${report.totalUsers}`, 60, y);

    pdf.text(`Total Sellers:`, 14, y + 10);
    pdf.text(`${report.totalSellers}`, 60, y + 10);

    pdf.text(`Total Products:`, 14, y + 20);
    pdf.text(`${report.totalProducts}`, 60, y + 20);

    // Right Column
    pdf.text(`Total Orders:`, 100, y);
    pdf.text(`${report.totalOrders}`, 145, y);

    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(162, 47, 41); // Red accent for revenue
    pdf.text(`Total Revenue:`, 100, y + 10);
    pdf.text(`$${Number(report.totalRevenue).toFixed(2)}`, 145, y + 10);

    // Divider line
    y += 35;
    pdf.setDrawColor(220, 220, 220);
    pdf.line(14, y, pageWidth - 14, y);

    // ==========================================
    // 4. TOP PRODUCTS LIST
    // ==========================================
    y += 15;
    pdf.setTextColor(30, 30, 30);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    pdf.text("Top 5 Best-Selling Products", 14, y);

    y += 12;
    pdf.setFontSize(11);

    report.topProducts.forEach((product, index) => {
      // Background row for alternate items
      if (index % 2 === 0) {
        pdf.setFillColor(245, 245, 245);
        pdf.rect(14, y - 5, pageWidth - 28, 10, "F");
      }

      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(100, 100, 100);
      pdf.text(`#${index + 1}`, 18, y);

      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(30, 30, 30);

      // Ensure product name is clean of Arabic to prevent crashes, or it will just strip it
      // Replace complex characters with standard English approximations if needed.
      const cleanName = product.name.replace(/[^\x00-\x7F]/g, "");
      pdf.text(`${cleanName || "Product Item"}`, 30, y);

      pdf.setFont("helvetica", "bold");
      pdf.text(`${product.totalSold} Sold`, pageWidth - 40, y);

      y += 10;
    });

    // ==========================================
    // 5. FOOTER
    // ==========================================
    pdf.setTextColor(150, 150, 150);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.text(
      "End of Report - Souq Yemen Internal Document",
      pageWidth / 2,
      280,
      { align: "center" },
    );

    pdf.save("SouqYemen_Admin_Report.pdf");
  };

  if (!report)
    return (
      <div className="text-center py-20 font-bold text-gray-500 animate-pulse">
        {t("Loading report...")}
      </div>
    );

  const StatCard = ({ title, value, icon: Icon, color }) => (
    <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm flex items-center gap-4 transition-transform hover:-translate-y-1">
      <div
        className={`w-14 h-14 rounded-xl flex items-center justify-center ${color}`}
      >
        <Icon size={28} />
      </div>
      <div>
        <p className="text-sm font-bold text-gray-500 uppercase tracking-wider">
          {title}
        </p>
        <p className="text-3xl font-black text-gray-900">{value}</p>
      </div>
    </div>
  );

  return (
    <div className="space-y-8 animate-[fadeSlideUp_0.4s_ease_forwards]">
      <div className="flex flex-col sm:flex-row items-center justify-between bg-white p-6 rounded-2xl border border-gray-200 shadow-sm gap-4">
        <div>
          <h3 className="text-2xl font-black text-gray-900">
            {t("Platform Overview")}
          </h3>
          <p className="text-gray-500 font-medium mt-1">
            {t("Key metrics across the entire marketplace.")}
          </p>
        </div>
        <button
          onClick={handleDownloadPDF}
          className="w-full sm:w-auto flex items-center justify-center gap-2 bg-[#a22f29] text-white px-6 py-3.5 rounded-xl font-bold hover:bg-[#832520] shadow-md transition-all active:scale-95"
        >
          <Download size={20} /> {t("Download Report")}
        </button>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <StatCard
          title={t("Total Revenue")}
          value={`$${Number(report.totalRevenue).toFixed(2)}`}
          icon={DollarSign}
          color="bg-green-100 text-green-700"
        />
        <StatCard
          title={t("Total Orders")}
          value={report.totalOrders}
          icon={ShoppingCart}
          color="bg-blue-100 text-blue-700"
        />
        <StatCard
          title={t("Total Products")}
          value={report.totalProducts}
          icon={Package}
          color="bg-purple-100 text-purple-700"
        />
        <StatCard
          title={t("Total Users")}
          value={report.totalUsers}
          icon={Users}
          color="bg-amber-100 text-amber-700"
        />
        <StatCard
          title={t("Total Sellers")}
          value={report.totalSellers}
          icon={Store}
          color="bg-[#f9eaea] text-[#a22f29]"
        />
      </div>

      {/* Top Products */}
      <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 bg-amber-100 text-amber-600 rounded-xl flex items-center justify-center">
            <Trophy size={20} />
          </div>
          <h3 className="text-xl font-black text-gray-900">
            {t("Top 5 Products")}
          </h3>
        </div>

        <div className="space-y-3">
          {report.topProducts.map((product, i) => (
            <div
              key={i}
              className="flex items-center justify-between p-4 bg-gray-50 rounded-xl border border-gray-100 hover:border-gray-300 transition-colors"
            >
              <span className="font-bold text-gray-800 flex items-center gap-4">
                <span className="w-8 h-8 rounded-full bg-white flex items-center justify-center text-sm font-black text-gray-400 shadow-sm border border-gray-100">
                  {i + 1}
                </span>
                {product.name}
              </span>
              <span className="font-black text-[#a22f29] bg-[#f9eaea] px-4 py-1.5 rounded-lg border border-[#f2d8d8]">
                {product.totalSold} {t("Sold")}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
